server:
  port: 8762

spring:
  application:
    name: msy-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    demo01:
      path: /demo01/** # 路径
      serviceId: msy-demo011112 # 服务名
    demo02:
      path: /demo02/** # 路径
      serviceId: msy-demo02